apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: testjava
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testjava
  template:
    metadata:
      labels:
        app: testjava
    spec:
      containers:
      - name: testjava
        image: testjava-image
        imagePullPolicy: Never
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: testjava-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: testjava
  externalTrafficPolicy: Local
  type: LoadBalancer