apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: testjava
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testjava
  template:
    metadata:
      labels:
        app: testjava
    spec:
      containers:
      - name: testjava
        image: testjava-image
        imagePullPolicy: Never